---
apiVersion: v1
kind: Secret
metadata:
  name: cloudsecret
type: Opaque
stringData:
  NX_CLOUD_MONGO_SERVER_ENDPOINT: "mongodb://127.0.0.1"
  ADMIN_PASSWORD: "SOME_ADMIN_PASSWORD"
  GITHUB_SECRET: "I_AM_A_SECRET_VALUE"
  GH_CLIENT_ID: "I_AM_A_SECRET_VALUE"
  GH_CLIENT_SECRET_VALUE: "I_AM_A_SECRET_VALUE"
  SOME_SECRET_TOKEN: "I_AM_A_SECRET_VALUE"
  GITLAB_ACCESS_TOKEN: "I_AM_A_SECRET_VALUE"