---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nx-cloud-external-secret
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: SecretStore
    name: nx-cloud-secret-store # the name of the store resource we created above
  target:
    name: nx-cloud-k8s-secret # need to match the secret name in your NxCloud helm-values.yaml
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: nx-cloud-secrets # name of your secret in the AWS Secret Manager