apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: nx-cloud-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1 # your cluster zone
      auth:
        jwt:
          serviceAccountRef:
            name: read-secrets-service-account