---
apiVersion: v1
kind: Service
metadata:
  name: nx-cloud-nx-api-service
  labels:
    app: nx-cloud-nx-api
    {{- include "nxCloud.app.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app: nx-cloud-nx-api
  ports:
    - port: 4203
      targetPort: 4203
