{{- if .Values.enableWorkflows }}
---
apiVersion: v1
kind: Service
metadata:
  name: nx-cloud-workflow-controller-service
  labels:
    app: nx-cloud-workflow-controller
    {{- include "nxCloud.app.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app: nx-workflow-controller
  ports:
    - port: 9000
      targetPort: 9000
{{- end }}