{{- if .Values.nxCloudWorkflows.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.nxCloudWorkflows.namespace }}
  labels:
    {{- include "nxCloud.app.labels" . | indent 4 }}
{{- end }}